"""integration and delta

Revision ID: de5695bb20c4
Revises: cf384fafa1e1
Create Date: 2024-10-15 22:35:50.297356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "de5695bb20c4"
down_revision: Union[str, None] = "cf384fafa1e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=True),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("auth_type", sa.String(), nullable=False),
        sa.Column("auth_schema", sa.String(), nullable=False),
        sa.Column(
            "credentials", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "integration_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_integrations_id"), "integrations", ["id"], unique=False)
    op.add_column(
        "agent_tools", sa.Column("integration_key", sa.String(), nullable=True)
    )
    op.add_column(
        "agent_tools",
        sa.Column(
            "tool_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("agent_tools", "additional_config")
    op.add_column("data_folders", sa.Column("icon", sa.String(), nullable=True))
    op.add_column("emails", sa.Column("remote_url", sa.String(), nullable=True))
    op.add_column("task_events", sa.Column("agent_task_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "task_events_agent_task_id_fkey",
        "task_events",
        "agent_tasks",
        ["agent_task_id"],
        ["id"],
    )
    op.add_column(
        "task_progress", sa.Column("started_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "task_progress", sa.Column("execution_time", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_progress", "execution_time")
    op.drop_column("task_progress", "started_at")
    op.drop_constraint(
        "task_events_agent_task_id_fkey", "task_events", type_="foreignkey"
    )
    op.drop_column("task_events", "agent_task_id")
    op.drop_column("emails", "remote_url")
    op.drop_column("data_folders", "icon")
    op.add_column(
        "agent_tools",
        sa.Column(
            "additional_config",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("agent_tools", "tool_config")
    op.drop_column("agent_tools", "integration_key")
    op.drop_index(op.f("ix_integrations_id"), table_name="integrations")
    op.drop_table("integrations")
    # ### end Alembic commands ###
