"""base migration

Revision ID: cf384fafa1e1
Revises:
Create Date: 2024-08-14 00:26:07.296748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cf384fafa1e1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_llms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("llm_key", sa.String(), nullable=False),
        sa.Column("data", JSON, nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("llm_key"),
    )
    op.create_index(op.f("ix_agent_llms_id"), "agent_llms", ["id"], unique=False)
    op.create_table(
        "agent_tools",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("tool_type", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=True),
        sa.Column("api_type", sa.String(), nullable=True),
        sa.Column("method", sa.String(), nullable=True),
        sa.Column("endpoint", sa.String(), nullable=True),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "path_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "query_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("body_template", sa.Text(), nullable=True),
        sa.Column("auth_type", sa.String(), nullable=True),
        sa.Column(
            "additional_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action"),
    )
    op.create_index(op.f("ix_agent_tools_id"), "agent_tools", ["id"], unique=False)
    op.create_table(
        "agents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", postgresql.CITEXT(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("intent_class", sa.String(), nullable=True),  # deprecated
        sa.Column("style", sa.String(), nullable=True),
        sa.Column("goal", sa.String(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("rules", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("data_templates", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("expected_output", sa.Text(), nullable=True),
        sa.Column("tools", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "knowledge_base", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("agent_llm", sa.String(), nullable=True),
        sa.Column("examples", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("mailbox_trigger", sa.String(), nullable=True),
        sa.Column(
            "agent_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("data_store", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("icon", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_agents_id"), "agents", ["id"], unique=False)
    op.create_table(
        "configurations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "environment", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_configurations_id"), "configurations", ["id"], unique=False
    )
    op.create_table(
        "data_folders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_root", sa.Boolean(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["data_folders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_data_folders_id"), "data_folders", ["id"], unique=False)
    op.create_table(
        "data_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("template_class", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("document_instruction", sa.Text(), nullable=True),
        sa.Column(
            "data_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("template_class"),
    )
    op.create_index(
        op.f("ix_data_templates_id"), "data_templates", ["id"], unique=False
    )
    op.create_table(
        "intents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("intent_class", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("intent_class"),
    )
    op.create_index(op.f("ix_intents_id"), "intents", ["id"], unique=False)
    op.create_table(
        "mailbox_polling",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email_id", sa.String(), nullable=True),
        sa.Column("folder", sa.String(), nullable=True),
        sa.Column("task_name", sa.String(), nullable=True),
        sa.Column("frequency", sa.Float(), nullable=True),
        sa.Column("delta_link", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("data_store", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "polling_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mailbox_polling_email_id"),
        "mailbox_polling",
        ["email_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mailbox_polling_id"), "mailbox_polling", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_mailbox_polling_task_name"),
        "mailbox_polling",
        ["task_name"],
        unique=True,
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("tenant_code", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("tenant_code"),
    )
    op.create_index(op.f("ix_organizations_id"), "organizations", ["id"], unique=False)
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("endpoints", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("data_filters", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("module", sa.String(), nullable=True),
        sa.Column("access_levels", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("web_routes", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_index(op.f("ix_permissions_id"), "permissions", ["id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("role_key", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("default_role", sa.Boolean(), nullable=True),
        sa.Column(
            "role_permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("role_key"),
    )
    op.create_index(op.f("ix_user_roles_id"), "user_roles", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("salt", sa.String(), nullable=True),
        sa.Column("account_status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=True)
    op.create_table(
        "authentications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_uuid", sa.UUID(), nullable=True),
        sa.Column("access_token", sa.String(), nullable=True),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_authentications_access_token"),
        "authentications",
        ["access_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authentications_id"), "authentications", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_authentications_refresh_token"),
        "authentications",
        ["refresh_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authentications_user_uuid"),
        "authentications",
        ["user_uuid"],
        unique=True,
    )
    op.create_table(
        "data_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=True),
        sa.Column("md5_hash", sa.String(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column(
            "external_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("folder_id", sa.UUID(), nullable=False),
        sa.Column("last_synced", sa.DateTime(), nullable=True),
        sa.Column("is_indexed", sa.Boolean(), nullable=False),
        sa.Column("indexed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["data_folders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("folder_id", "name", name="uq_folder_file"),
    )
    op.create_index(op.f("ix_data_files_id"), "data_files", ["id"], unique=False)
    op.create_table(
        "emails",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email_id", sa.String(), nullable=True),
        sa.Column("message_id", sa.String(), nullable=True),
        sa.Column("conversation_id", sa.String(), nullable=True),
        sa.Column("mailbox_email", sa.String(), nullable=True),
        sa.Column("mailbox_folder", sa.String(), nullable=True),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("sender_name", sa.String(), nullable=True),
        sa.Column("sender_email", sa.String(), nullable=True),
        sa.Column("web_link", sa.String(), nullable=True),
        sa.Column("email_body", sa.Text(), nullable=True),
        sa.Column("intent_class", sa.String(), nullable=True),
        sa.Column("data_template", sa.String(), nullable=True),
        sa.Column("records", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("credits_used", sa.Integer(), nullable=True),
        sa.Column("task_status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emails_conversation_id"), "emails", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_emails_email_id"), "emails", ["email_id"], unique=False)
    op.create_index(op.f("ix_emails_id"), "emails", ["id"], unique=False)
    op.create_index(
        op.f("ix_emails_mailbox_email"), "emails", ["mailbox_email"], unique=False
    )
    op.create_index(op.f("ix_emails_message_id"), "emails", ["message_id"], unique=True)
    op.create_table(
        "user_access",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("role_id", sa.UUID(), nullable=True),
        sa.Column(
            "data_access", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["user_roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_access_id"), "user_access", ["id"], unique=False)
    op.create_table(
        "agent_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email_data_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("credits_used", sa.Integer(), nullable=True),
        sa.Column("executed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["email_data_id"],
            ["emails.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_tasks_id"), "agent_tasks", ["id"], unique=False)
    op.create_table(
        "attachments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email_data_id", sa.UUID(), nullable=True),
        sa.Column("attachment_id", sa.String(), nullable=True),
        sa.Column("message_id", sa.String(), nullable=True),
        sa.Column("conversation_id", sa.String(), nullable=True),
        sa.Column("content_id", sa.String(), nullable=True),
        sa.Column("file_name", sa.String(), nullable=True),
        sa.Column("file_type", sa.String(), nullable=True),
        sa.Column("remote_url", sa.String(), nullable=True),
        sa.Column("content", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "mapping_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("ai_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ocr_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("template_class", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["email_data_id"],
            ["emails.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attachments_id"), "attachments", ["id"], unique=False)
    op.create_index(
        op.f("ix_attachments_message_id"), "attachments", ["message_id"], unique=False
    )
    op.create_table(
        "task_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email_data_id", sa.UUID(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["email_data_id"],
            ["emails.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_events_id"), "task_events", ["id"], unique=False)
    op.create_table(
        "task_progress",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email_data_id", sa.UUID(), nullable=True),
        sa.Column("step_order", sa.Integer(), nullable=True),
        sa.Column("step_code", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("executed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["email_data_id"],
            ["emails.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_progress_id"), "task_progress", ["id"], unique=False)
    op.create_table(
        "agent_outputs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email_data_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("agent_task_id", sa.UUID(), nullable=True),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("task_summary", sa.Text(), nullable=True),
        sa.Column(
            "agent_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "agent_environment", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "agent_memory", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("credits_used", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["agent_task_id"],
            ["agent_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["email_data_id"],
            ["emails.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_outputs_id"), "agent_outputs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_outputs_id"), table_name="agent_outputs")
    op.drop_table("agent_outputs")
    op.drop_index(op.f("ix_task_progress_id"), table_name="task_progress")
    op.drop_table("task_progress")
    op.drop_index(op.f("ix_task_events_id"), table_name="task_events")
    op.drop_table("task_events")
    op.drop_index(op.f("ix_attachments_message_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index(op.f("ix_agent_tasks_id"), table_name="agent_tasks")
    op.drop_table("agent_tasks")
    op.drop_index(op.f("ix_user_access_id"), table_name="user_access")
    op.drop_table("user_access")
    op.drop_index(op.f("ix_emails_message_id"), table_name="emails")
    op.drop_index(op.f("ix_emails_mailbox_email"), table_name="emails")
    op.drop_index(op.f("ix_emails_id"), table_name="emails")
    op.drop_index(op.f("ix_emails_email_id"), table_name="emails")
    op.drop_index(op.f("ix_emails_conversation_id"), table_name="emails")
    op.drop_table("emails")
    op.drop_index(op.f("ix_data_files_id"), table_name="data_files")
    op.drop_table("data_files")
    op.drop_index(op.f("ix_authentications_user_uuid"), table_name="authentications")
    op.drop_index(
        op.f("ix_authentications_refresh_token"), table_name="authentications"
    )
    op.drop_index(op.f("ix_authentications_id"), table_name="authentications")
    op.drop_index(op.f("ix_authentications_access_token"), table_name="authentications")
    op.drop_table("authentications")
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_user_roles_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_permissions_id"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_organizations_id"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_mailbox_polling_task_name"), table_name="mailbox_polling")
    op.drop_index(op.f("ix_mailbox_polling_id"), table_name="mailbox_polling")
    op.drop_index(op.f("ix_mailbox_polling_email_id"), table_name="mailbox_polling")
    op.drop_table("mailbox_polling")
    op.drop_index(op.f("ix_intents_id"), table_name="intents")
    op.drop_table("intents")
    op.drop_index(op.f("ix_data_templates_id"), table_name="data_templates")
    op.drop_table("data_templates")
    op.drop_index(op.f("ix_data_folders_id"), table_name="data_folders")
    op.drop_table("data_folders")
    op.drop_index(op.f("ix_configurations_id"), table_name="configurations")
    op.drop_table("configurations")
    op.drop_index(op.f("ix_agents_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_agent_tools_id"), table_name="agent_tools")
    op.drop_table("agent_tools")
    op.drop_index(op.f("ix_agent_llms_id"), table_name="agent_llms")
    op.drop_table("agent_llms")
    # ### end Alembic commands ###
