"""remove the task progress table and add the events column in the emails table

Revision ID: a160e97b6383
Revises: 6ab03af605bd
Create Date: 2025-09-13 16:32:00.163290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a160e97b6383"
down_revision: Union[str, None] = "6ab03af605bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_progress_id", table_name="task_progress")
    op.drop_table("task_progress")

    # Create version_history table
    op.create_table(
        "version_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "config_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_entity_version",
        "version_history",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_version_history_id", "version_history", ["id"], unique=False)
    op.create_index(
        "ix_version_history_entity_type",
        "version_history",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        "ix_version_history_entity_id", "version_history", ["entity_id"], unique=False
    )
    op.create_index(
        "ix_version_history_user_id", "version_history", ["user_id"], unique=False
    )
    op.create_index(
        "ix_version_history_created_at", "version_history", ["created_at"], unique=False
    )

    # --- Drop old columns from task_events ---
    op.drop_constraint(
        "task_events_agent_task_id_fkey", "task_events", type_="foreignkey"
    )
    op.drop_column("task_events", "agent_task_id")
    op.drop_column("task_events", "message")
    op.drop_column("task_events", "event_type")
    op.drop_column("task_events", "updated_at")

    # --- Add new columns to task_events ---
    op.add_column("task_events", sa.Column("name", sa.String(), nullable=True))
    op.add_column("task_events", sa.Column("key", sa.String(), nullable=True))
    op.add_column("task_events", sa.Column("count", sa.Integer(), nullable=True))
    op.add_column(
        "task_events",
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop version_history table
    op.drop_index("ix_version_history_created_at", table_name="version_history")
    op.drop_index("ix_version_history_user_id", table_name="version_history")
    op.drop_index("ix_version_history_entity_id", table_name="version_history")
    op.drop_index("ix_version_history_entity_type", table_name="version_history")
    op.drop_index("ix_version_history_id", table_name="version_history")
    op.drop_index("idx_entity_version", table_name="version_history")
    op.drop_table("version_history")

    op.create_table(
        "task_progress",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email_data_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("step_order", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("step_code", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "executed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "started_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("execution_time", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["email_data_id"], ["emails.id"], name="task_progress_email_data_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="task_progress_pkey"),
    )
    op.create_index("ix_task_progress_id", "task_progress", ["id"], unique=False)

    # --- Re-add removed columns in task_events ---
    op.add_column("task_events", sa.Column("agent_task_id", sa.UUID(), nullable=True))
    op.add_column("task_events", sa.Column("message", sa.String(), nullable=True))
    op.add_column("task_events", sa.Column("event_type", sa.String(), nullable=True))
    op.add_column("task_events", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.create_foreign_key(
        "task_events_agent_task_id_fkey",
        "task_events",
        "agent_tasks",
        ["agent_task_id"],
        ["id"],
    )

    # --- Drop new columns ---
    op.drop_column("task_events", "name")
    op.drop_column("task_events", "key")
    op.drop_column("task_events", "count")
    op.drop_column("task_events", "additional_data")

    # ### end Alembic commands ###
