"""agent framework 2

Revision ID: 6ab03af605bd
Revises: de5695bb20c4
Create Date: 2025-05-21 06:34:59.933019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6ab03af605bd"
down_revision: Union[str, None] = "de5695bb20c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_collections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("index_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("is_root", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "collection_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "smart_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "knowledge_topics", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("owner_id", sa.String(), nullable=True),
        sa.Column(
            "availability", sa.String(), server_default="UNLISTED", nullable=True
        ),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["data_collections.id"],
            name="data_collections_parent_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_collections_id"), "data_collections", ["id"], unique=False
    )

    # Modify data_files table: drop old constraints, rename folder_id, and add new constraints
    with op.batch_alter_table("data_files") as batch_op:
        # Drop the old foreign key constraint
        batch_op.drop_constraint("data_files_folder_id_fkey", type_="foreignkey")
        # Drop the old unique constraint
        batch_op.drop_constraint("uq_folder_file", type_="unique")
        # Rename folder_id to collection_id
        batch_op.alter_column("folder_id", new_column_name="collection_id")
        # Rename external_metadata to file_metadata
        batch_op.alter_column("external_metadata", new_column_name="file_metadata")
        # Rename source to source_type
        batch_op.alter_column("source", new_column_name="source_type")
        # Create the new unique constraint
        batch_op.create_unique_constraint(
            "uq_collection_file", ["collection_id", "name"]
        )
        # Create the new foreign key
        batch_op.create_foreign_key(
            "data_files_collection_id_fkey",
            "data_collections",
            ["collection_id"],
            ["id"],
        )

    # Now safe to drop data_folders table
    op.drop_index("ix_data_folders_id", table_name="data_folders")
    op.drop_table("data_folders")

    op.add_column(
        "agent_outputs",
        sa.Column(
            "execution_log", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column("agent_outputs", sa.Column("thread_id", sa.String(), nullable=True))
    op.drop_constraint(
        "agent_outputs_email_data_id_fkey", "agent_outputs", type_="foreignkey"
    )
    op.drop_column("agent_outputs", "agent_environment")
    op.drop_column("agent_outputs", "email_data_id")
    op.drop_column("agent_outputs", "agent_memory")
    op.create_unique_constraint(
        "uq_agent_outputs_thread_id", "agent_outputs", ["thread_id"]
    )
    op.add_column("agent_tasks", sa.Column("thread_id", sa.String(), nullable=True))
    op.add_column(
        "agent_tasks",
        sa.Column(
            "attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # Rename data to additional_data
    op.alter_column("agent_tasks", "data", new_column_name="additional_data")
    # Rename executed_at to completed_at
    op.alter_column("agent_tasks", "executed_at", new_column_name="completed_at")
    op.add_column("agent_tasks", sa.Column("task_order", sa.String(), nullable=True))
    op.add_column("agent_tasks", sa.Column("notes", sa.Text(), nullable=True))
    op.create_unique_constraint(
        "uq_agent_tasks_thread_id", "agent_tasks", ["thread_id"]
    )
    op.add_column(
        "agent_tools", sa.Column("tags", sa.ARRAY(sa.String()), nullable=True)
    )
    op.drop_column("agent_tools", "tool_type")
    op.add_column(
        "agents",
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "agents", sa.Column("reviewers", sa.ARRAY(sa.String()), nullable=True)
    )
    op.add_column(
        "agents",
        sa.Column(
            "response_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # Rename mailbox_trigger to agent_mailbox
    op.alter_column("agents", "mailbox_trigger", new_column_name="agent_mailbox")
    # Rename expected_output to success_criteria
    op.alter_column("agents", "expected_output", new_column_name="success_criteria")
    op.add_column("attachments", sa.Column("size", sa.Integer(), nullable=True))
    op.add_column(
        "attachments", sa.Column("ocr_content", sa.ARRAY(sa.Text()), nullable=True)
    )
    op.add_column(
        "attachments",
        sa.Column(
            "structured_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column("attachments", sa.Column("ocr_corrections", sa.Text(), nullable=True))
    op.drop_column("attachments", "content_id")
    op.drop_column("configurations", "environment")
    op.add_column(
        "data_files",
        sa.Column(
            "acl_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "data_files",
        sa.Column("status", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column(
        "data_files",
        sa.Column(
            "source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("data_files", "indexed_at")
    op.drop_column("data_files", "is_indexed")
    op.drop_column("data_files", "file_path")
    # Rename task_status to status
    op.alter_column("emails", "task_status", new_column_name="status")
    op.add_column("emails", sa.Column("source_type", sa.String(), nullable=True))
    op.add_column("emails", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "emails",
        sa.Column(
            "additional_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("emails", "remote_url")
    op.drop_column("emails", "sender_email")
    op.drop_column("emails", "sent_at")
    op.drop_column("emails", "intent_class")
    op.add_column("integrations", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column(
        "integrations", sa.Column("service_types", sa.ARRAY(sa.String()), nullable=True)
    )
    op.create_index(op.f("ix_integrations_key"), "integrations", ["key"], unique=False)
    op.add_column(
        "organizations",
        sa.Column(
            "contact_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "organizations", sa.Column("db_schema", sa.String(length=255), nullable=False)
    )
    op.alter_column(
        "organizations",
        "address",
        existing_type=sa.VARCHAR(length=255),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="address::jsonb",
    )
    op.drop_column("organizations", "city")
    op.drop_column("organizations", "industry")
    op.drop_column("organizations", "state")
    op.drop_column("organizations", "postal_code")
    op.drop_column("organizations", "website")
    op.drop_column("organizations", "country")
    op.drop_column("organizations", "phone_number")
    op.drop_column("organizations", "email")
    op.create_unique_constraint(
        "uq_organizations_db_schema", "organizations", ["db_schema"]
    )
    op.drop_index("ix_authentications_user_uuid", table_name="authentications")
    op.create_index(
        op.f("ix_authentications_user_uuid"),
        "authentications",
        ["user_uuid"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column(
            "user_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("activity_type", sa.String(), nullable=False),
        sa.Column(
            "previous_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("new_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "activity_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_entity_activity",
        "activity_logs",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_logs_activity_type"),
        "activity_logs",
        ["activity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_logs_created_at"),
        "activity_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_logs_entity_id"), "activity_logs", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_logs_entity_type"),
        "activity_logs",
        ["entity_type"],
        unique=False,
    )
    op.create_index(op.f("ix_activity_logs_id"), "activity_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_activity_logs_user_id"), "activity_logs", ["user_id"], unique=False
    )
    op.create_table(
        "chat_histories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "chat_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(
        "idx_chat_history_id_created_at",
        "chat_histories",
        ["id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_histories_id"), "chat_histories", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_histories_user_id"), "chat_histories", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_histories_parent_id"),
        "chat_histories",
        ["parent_id"],
        unique=False,
    )
    op.create_table(
        "class_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "class_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_index(op.f("ix_class_groups_id"), "class_groups", ["id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recipient_id", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("notification_type", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("template_key", sa.String(), nullable=True),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column(
            "delivery_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_entity_id"), "notifications", ["entity_id"], unique=False
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_index(
        op.f("ix_notifications_notification_type"),
        "notifications",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_recipient_id"),
        "notifications",
        ["recipient_id"],
        unique=False,
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chat_history_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "message_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["chat_history_id"], ["chat_histories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_chat_messages_chat_history_id"),
        "chat_messages",
        ["chat_history_id"],
        unique=False,
    )
    op.add_column(
        "user_access",
        sa.Column("app_access", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column(
            "tag_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_id"), "tags", ["id"], unique=False)
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.add_column(
        "agent_tasks", sa.Column("tag_ids", sa.ARRAY(sa.String()), nullable=True)
    )
    op.add_column("emails", sa.Column("tag_ids", sa.ARRAY(sa.String()), nullable=True))
    op.add_column("chat_histories", sa.Column("chat_type", sa.String(), nullable=True))
    op.create_table(
        "user_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "data_access", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("app_access", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_groups_id"), "user_groups", ["id"], unique=False)
    op.create_index(op.f("ix_user_groups_key"), "user_groups", ["key"], unique=True)
    op.create_index(op.f("ix_user_groups_name"), "user_groups", ["name"], unique=True)
    op.add_column(
        "user_access",
        sa.Column("user_group_ids", postgresql.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_access", "user_group_ids")
    op.drop_index(op.f("ix_user_groups_name"), table_name="user_groups")
    op.drop_index(op.f("ix_user_groups_key"), table_name="user_groups")
    op.drop_index(op.f("ix_user_groups_id"), table_name="user_groups")
    op.drop_table("user_groups")
    op.drop_column("chat_histories", "chat_type")
    op.drop_column("emails", "tag_ids")
    op.drop_column("agent_tasks", "tag_ids")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_index(op.f("ix_tags_id"), table_name="tags")
    op.drop_table("tags")
    op.drop_column("user_access", "app_access")
    op.drop_column("users", "user_config")
    op.drop_index("ix_authentications_user_uuid", table_name="authentications")
    op.create_index(
        op.f("ix_authentications_user_uuid"),
        "authentications",
        ["user_uuid"],
        unique=True,
    )
    op.drop_constraint("uq_organizations_db_schema", "organizations", type_="unique")
    op.alter_column(
        "organizations",
        "address",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("organizations", "db_schema")
    op.drop_column("organizations", "contact_info")
    op.add_column(
        "organizations",
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "phone_number", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "country", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "website", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "postal_code", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "organizations",
        sa.Column("state", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "industry", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "organizations",
        sa.Column("city", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_integrations_key"), table_name="integrations")
    op.drop_column("integrations", "service_types")
    op.drop_column("integrations", "is_active")
    op.add_column(
        "emails",
        sa.Column("intent_class", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "emails",
        sa.Column(
            "sent_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "emails",
        sa.Column("sender_email", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "emails",
        sa.Column("remote_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column("emails", "status", new_column_name="task_status")
    op.drop_column("emails", "additional_data")
    op.drop_column("emails", "notes")
    op.drop_column("emails", "source_type")
    op.add_column(
        "data_files",
        sa.Column("file_path", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "data_files",
        sa.Column("is_indexed", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "data_files",
        sa.Column(
            "indexed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    # Recreate data_folders table
    op.create_table(
        "data_folders",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("is_root", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("parent_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("icon", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["data_folders.id"], name="data_folders_parent_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="data_folders_pkey"),
    )
    op.create_index("ix_data_folders_id", "data_folders", ["id"], unique=False)
    # Revert data_files changes
    with op.batch_alter_table("data_files") as batch_op:
        # Drop the new foreign key constraint
        batch_op.drop_constraint("data_files_collection_id_fkey", type_="foreignkey")
        # Drop the new unique constraint
        batch_op.drop_constraint("uq_collection_file", type_="unique")
        # Rename collection_id back to folder_id
        batch_op.alter_column("collection_id", new_column_name="folder_id")
        # Rename file_metadata back to external_metadata
        batch_op.alter_column("file_metadata", new_column_name="external_metadata")
        # Rename source_type back to source
        batch_op.alter_column("source_type", new_column_name="source")
        # Create the original unique constraint
        batch_op.create_unique_constraint("uq_folder_file", ["folder_id", "name"])
        # Create the original foreign key
        batch_op.create_foreign_key(
            "data_files_folder_id_fkey",
            "data_folders",
            ["folder_id"],
            ["id"],
        )
    op.drop_column("data_files", "source_metadata")
    op.drop_column("data_files", "status")
    op.drop_column("data_files", "acl_metadata")
    op.add_column(
        "configurations",
        sa.Column(
            "environment",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "attachments",
        sa.Column("content_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("attachments", "ocr_corrections")
    op.drop_column("attachments", "structured_output")
    op.drop_column("attachments", "ocr_content")
    op.drop_column("attachments", "size")
    op.alter_column("agents", "success_criteria", new_column_name="expected_output")
    op.alter_column("agents", "agent_mailbox", new_column_name="mailbox_trigger")
    op.drop_column("agents", "response_schema")
    op.drop_column("agents", "reviewers")
    op.drop_column("agents", "plan")
    op.add_column(
        "agent_tools",
        sa.Column("tool_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("agent_tools", "tags")
    op.alter_column("agent_tasks", "completed_at", new_column_name="executed_at")
    op.alter_column("agent_tasks", "additional_data", new_column_name="data")
    op.drop_column("agent_tasks", "notes")
    op.drop_column("agent_tasks", "task_order")
    op.drop_column("agent_tasks", "attachments")
    op.drop_constraint("uq_agent_tasks_thread_id", "agent_tasks", type_="unique")
    op.drop_column("agent_tasks", "thread_id")
    op.add_column(
        "agent_outputs",
        sa.Column(
            "agent_memory",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "agent_outputs",
        sa.Column("email_data_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "agent_outputs",
        sa.Column(
            "agent_environment",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "agent_outputs_email_data_id_fkey",
        "agent_outputs",
        "emails",
        ["email_data_id"],
        ["id"],
    )
    op.drop_column("agent_outputs", "execution_log")
    op.drop_column("agent_outputs", "thread_id")
    op.drop_column("data_collections", "knowledge_topics")
    op.drop_column("data_collections", "smart_fields")
    op.drop_index(op.f("ix_data_collections_id"), table_name="data_collections")
    op.drop_table("data_collections")
    op.drop_index(op.f("ix_chat_messages_chat_history_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_notifications_recipient_id"), table_name="notifications")
    op.drop_index(
        op.f("ix_notifications_notification_type"), table_name="notifications"
    )
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_entity_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_class_groups_id"), table_name="class_groups")
    op.drop_table("class_groups")
    op.drop_index(op.f("ix_chat_histories_parent_id"), table_name="chat_histories")
    op.drop_index(op.f("ix_chat_histories_user_id"), table_name="chat_histories")
    op.drop_index(op.f("ix_chat_histories_id"), table_name="chat_histories")
    op.drop_index("idx_chat_history_id_created_at", table_name="chat_histories")
    op.drop_table("chat_histories")
    op.drop_index(op.f("ix_activity_logs_user_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_entity_type"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_entity_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_created_at"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_activity_type"), table_name="activity_logs")
    op.drop_index("idx_entity_activity", table_name="activity_logs")
    op.drop_table("activity_logs")
    # ### end Alembic commands ###
