"""Process optimization

Revision ID: 03dafa6a220a
Revises: 3a403f9215f7
Create Date: 2026-05-14 13:12:18.771932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "03dafa6a220a"
down_revision: Union[str, None] = "3a403f9215f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configurations",
        sa.Column(
            "auth_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "agent_tools",
        sa.Column(
            "auth_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_tools", "auth_config")
    op.drop_column("configurations", "auth_config")
    # ### end Alembic commands ###
