"""integrations and triggers

Revision ID: 3a403f9215f7
Revises: af05779232de
Create Date: 2026-03-24 09:48:04.944263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a403f9215f7'
down_revision: Union[str, None] = 'af05779232de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False, comment='Validated against ALL_INTEGRATIONS registry at runtime'),
    sa.Column('auth_schema_key', sa.String(length=64), nullable=False, comment="References AUTH_SCHEMAS registry (e.g., 'msft.oauth2.app_only')"),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False, comment='Fernet-encrypted user inputs: client_id, client_secret, api_keys, etc.'),
    sa.Column('encrypted_token', sa.Text(), nullable=True, comment='Fernet-encrypted OAuth tokens: access_token, refresh_token, expires_at'),
    sa.Column('connection_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Provider-specific non-sensitive config: region, tenant_id, instance_url'),
    sa.Column('connection_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Operational context: validation_attempts, error_details, reauth_history'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='User-controlled enable/disable toggle'),
    sa.Column('auth_status', sa.String(length=32), nullable=False, comment='System-managed: valid, expired, invalid, reauth_required'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp for audit trail'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last TaskSource poll or ToolBinding invocation'),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful authentication check'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_auth_schema_key'), 'connections', ['auth_schema_key'], unique=False)
    op.create_index(op.f('ix_connections_auth_status'), 'connections', ['auth_status'], unique=False)
    op.create_index(op.f('ix_connections_deleted_at'), 'connections', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_connections_is_active'), 'connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_connections_provider_key'), 'connections', ['provider_key'], unique=False)
    op.create_table('task_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False, comment='Denormalized from connection for efficient queries'),
    sa.Column('trigger_key', sa.String(length=128), nullable=False, comment="References TRIGGERS registry (e.g., 'outlook.new_email')"),
    sa.Column('name', sa.String(length=255), nullable=False, comment='User-visible label'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description'),
    sa.Column('resource_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='What to watch: mailbox+folder, bucket+prefix, object+query'),
    sa.Column('filter_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Event filters: sender domains, attachment types, field conditions'),
    sa.Column('schedule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Polling interval, cron, jitter, backoff'),
    sa.Column('processing_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Event processing: include body, download attachments, field selection'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='User-controlled on/off toggle'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Health status: ok, warn, error, auth_error'),
    sa.Column('cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Polling state: delta_token, timestamp, offset, history_id'),
    sa.Column('task_source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Operational context: polling_metrics, adapter_version, error_history, rate_limits'),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True, comment='Last adapter execution time'),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful event ingestion'),
    sa.Column('error_count', sa.Integer(), nullable=False, comment='Consecutive errors for exponential backoff'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Last error message for debugging'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Optional labels for filtering/grouping'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp for audit trail'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_sources_agent_id'), 'task_sources', ['agent_id'], unique=False)
    op.create_index(op.f('ix_task_sources_connection_id'), 'task_sources', ['connection_id'], unique=False)
    op.create_index(op.f('ix_task_sources_deleted_at'), 'task_sources', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_task_sources_enabled'), 'task_sources', ['enabled'], unique=False)
    op.create_index(op.f('ix_task_sources_id'), 'task_sources', ['id'], unique=False)
    op.create_index(op.f('ix_task_sources_provider_key'), 'task_sources', ['provider_key'], unique=False)
    op.create_index(op.f('ix_task_sources_status'), 'task_sources', ['status'], unique=False)
    op.create_index(op.f('ix_task_sources_trigger_key'), 'task_sources', ['trigger_key'], unique=False)
    op.create_table('tool_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False, comment='Denormalized from connection for efficient queries'),
    sa.Column('tool_key', sa.String(length=128), nullable=False, comment="References TOOLS registry (e.g., 'outlook.send_email')"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'tool_key', name='uq_agent_tool_key')
    )
    op.create_index(op.f('ix_tool_bindings_agent_id'), 'tool_bindings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tool_bindings_connection_id'), 'tool_bindings', ['connection_id'], unique=False)
    op.create_index(op.f('ix_tool_bindings_id'), 'tool_bindings', ['id'], unique=False)
    op.create_index(op.f('ix_tool_bindings_provider_key'), 'tool_bindings', ['provider_key'], unique=False)
    op.create_index(op.f('ix_tool_bindings_tool_key'), 'tool_bindings', ['tool_key'], unique=False)
    op.create_table('event_inbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_source_id', sa.UUID(), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=False, comment='Provider-native event ID (e.g., Graph message ID, S3 ETag)'),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False, comment='Unique key for deduplication (e.g., task_source_id:external_event_id)'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Normalized event payload (what the agent processes)'),
    sa.Column('event_inbox_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Processing context: trace_ids, attempts_history, routing, ingestion_stats'),
    sa.Column('status', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Processing progress: state, attempts, last_attempt_at, errors, progress, worker_id'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='When the event was successfully processed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Last error message (deprecated - use status.last_error instead)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_source_id'], ['task_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_event_inbox_dedupe_key')
    )
    op.create_index(op.f('ix_event_inbox_created_at'), 'event_inbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_inbox_dedupe_key'), 'event_inbox', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_event_inbox_id'), 'event_inbox', ['id'], unique=False)
    op.create_index(op.f('ix_event_inbox_task_source_id'), 'event_inbox', ['task_source_id'], unique=False)
    op.execute("DROP TABLE IF EXISTS attachments_backup")
    op.alter_column('activity_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('agent_llms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('agent_llms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('agent_outputs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('agent_outputs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('agent_tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('agent_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('agent_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('agent_tools', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_tools', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('agent_tools', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('agents', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('agents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('attachments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('authentications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('authentications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('chat_histories', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chat_histories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_histories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('class_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('class_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('configurations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('configurations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('data_collections', 'is_root',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('data_collections', 'smart_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('data_collections', 'knowledge_topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('data_collections', 'availability',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'UNLISTED'::character varying"))
    op.alter_column('data_collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('data_collections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('data_files', 'last_synced',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('data_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('data_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('data_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('data_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('data_templates', 'document_instruction',
               new_column_name='document_instructions',
               existing_type=sa.Text(),
               existing_nullable=True)
    op.alter_column('data_templates', 'document_instructions',
               existing_type=sa.Text(),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using=(
                   "string_to_array(nullif(trim(document_instructions), ''), E'\\n')"
               ))
    op.execute(
        """
        UPDATE data_templates AS dt
        SET document_instructions = sub.norm
        FROM (
            SELECT id,
                (SELECT (array_agg(trim(x)) FILTER (WHERE trim(x) <> ''))::character varying[]
                 FROM unnest(dt2.document_instructions) AS x) AS norm
            FROM data_templates AS dt2
        ) AS sub
        WHERE dt.id = sub.id
          AND dt.document_instructions IS NOT NULL
          AND sub.norm IS DISTINCT FROM dt.document_instructions
        """
    )
    op.alter_column('emails', 'received_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('emails', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('emails', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('emails', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('integrations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('integrations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('intents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('intents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('issue_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('issue_comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('mailbox_polling', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mailbox_polling', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('mailbox_polling', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('organizations', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('task_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('user_access', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('user_access', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('user_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('user_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('user_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('user_roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('users', 'account_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('version_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('version_history', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'account_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_roles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_roles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_groups', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_groups', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_access', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_access', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('task_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tags', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tags', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('permissions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('permissions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('organizations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('organizations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('organizations', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('notifications', 'sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('mailbox_polling', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('mailbox_polling', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('mailbox_polling', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('issues', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('issues', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('issue_comments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('issue_comments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('intents', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('intents', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('integrations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('integrations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('integrations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('emails', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('emails', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('emails', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('emails', 'received_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('data_templates', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('data_templates', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('data_templates', 'document_instructions',
               existing_type=sa.ARRAY(sa.String()),
               type_=sa.Text(),
               existing_nullable=True,
               postgresql_using='array_to_string(document_instructions, E\'\\n\')')
    op.alter_column('data_templates', 'document_instructions',
               new_column_name='document_instruction',
               existing_type=sa.Text(),
               existing_nullable=True)
    op.alter_column('data_files', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('data_files', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('data_files', 'last_synced',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('data_collections', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('data_collections', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('data_collections', 'availability',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'UNLISTED'::character varying"))
    op.alter_column('data_collections', 'knowledge_topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('data_collections', 'smart_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('data_collections', 'is_root',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('configurations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('configurations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('class_groups', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('class_groups', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('chat_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_histories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_histories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_histories', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('authentications', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('authentications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('attachments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('attachments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('api_keys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('agents', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('agents', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('agent_tools', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('agent_tools', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('agent_tools', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_tasks', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('agent_tasks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('agent_tasks', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('agent_outputs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('agent_outputs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('agent_llms', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('agent_llms', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('activity_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_event_inbox_task_source_id'), table_name='event_inbox')
    op.drop_index(op.f('ix_event_inbox_id'), table_name='event_inbox')
    op.drop_index(op.f('ix_event_inbox_dedupe_key'), table_name='event_inbox')
    op.drop_index(op.f('ix_event_inbox_created_at'), table_name='event_inbox')
    op.drop_table('event_inbox')
    op.drop_index(op.f('ix_tool_bindings_tool_key'), table_name='tool_bindings')
    op.drop_index(op.f('ix_tool_bindings_provider_key'), table_name='tool_bindings')
    op.drop_index(op.f('ix_tool_bindings_id'), table_name='tool_bindings')
    op.drop_index(op.f('ix_tool_bindings_connection_id'), table_name='tool_bindings')
    op.drop_index(op.f('ix_tool_bindings_agent_id'), table_name='tool_bindings')
    op.drop_table('tool_bindings')
    op.drop_index(op.f('ix_task_sources_trigger_key'), table_name='task_sources')
    op.drop_index(op.f('ix_task_sources_status'), table_name='task_sources')
    op.drop_index(op.f('ix_task_sources_provider_key'), table_name='task_sources')
    op.drop_index(op.f('ix_task_sources_id'), table_name='task_sources')
    op.drop_index(op.f('ix_task_sources_enabled'), table_name='task_sources')
    op.drop_index(op.f('ix_task_sources_deleted_at'), table_name='task_sources')
    op.drop_index(op.f('ix_task_sources_connection_id'), table_name='task_sources')
    op.drop_index(op.f('ix_task_sources_agent_id'), table_name='task_sources')
    op.drop_table('task_sources')
    op.drop_index(op.f('ix_connections_provider_key'), table_name='connections')
    op.drop_index(op.f('ix_connections_is_active'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_deleted_at'), table_name='connections')
    op.drop_index(op.f('ix_connections_auth_status'), table_name='connections')
    op.drop_index(op.f('ix_connections_auth_schema_key'), table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
