AGENT_LLMS = [
    {
        "openai": [
            {
                "name": "OpenAI GPT-5.4",
                "description": "OpenAI GPT-5.4 is an advanced large language model with enhanced reasoning and multimodal capabilities, suited to complex professional and coding workloads.",
                "llm_key": "openai/gpt-5.4",
                "integration_key": "openai",
                "model_name": "gpt-5.4",
                "provider": "openai",
                "llm_config": {
                    "temperature": "__unsupported__",
                },
                "metadata": {
                    "max_tokens": 1050000,
                    "max_output_tokens": 128000,
                    "intelligence": 5,
                    "speed": 3,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "structured_outputs",
                        "reasoning",
                    ],
                },
            },
            {
                "name": "OpenAI GPT-5.4 Mini",
                "description": "OpenAI GPT-5.4 Mini is a compact version of GPT-5.4 optimized for cost and speed.",
                "llm_key": "openai/gpt-5.4-mini",
                "integration_key": "openai",
                "model_name": "gpt-5.4-mini",
                "provider": "openai",
                "llm_config": {
                    "temperature": "__unsupported__",
                },
                "metadata": {
                    "max_tokens": 400000,
                    "max_output_tokens": 128000,
                    "intelligence": 4,
                    "speed": 4,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "structured_outputs",
                        "reasoning",
                    ],
                },
            },
            {
                "name": "OpenAI GPT-5.4 Nano",
                "description": "OpenAI GPT-5.4 Nano is the smallest and most efficient version of GPT-5.4, optimized for high-volume and low-latency tasks.",
                "llm_key": "openai/gpt-5.4-nano",
                "integration_key": "openai",
                "model_name": "gpt-5.4-nano",
                "provider": "openai",
                "llm_config": {
                    "temperature": "__unsupported__",
                },
                "metadata": {
                    "max_tokens": 400000,
                    "max_output_tokens": 128000,
                    "intelligence": 3,
                    "speed": 5,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "structured_outputs",
                        "reasoning",
                    ],
                },
            },
            {
                "name": "OpenAI GPT-5",
                "description": "OpenAI GPT-5 is an advanced large language model with enhanced capabilities.",
                "llm_key": "openai/gpt-5",
                "integration_key": "openai",
                "model_name": "gpt-5",
                "provider": "openai",
                "llm_config": {
                    "temperature": "__unsupported__",
                },
                "metadata": {
                    "max_tokens": 400000,
                    "max_output_tokens": 128000,
                    "intelligence": 5,
                    "speed": 3,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "structured_outputs",
                        "reasoning",
                    ],
                },
            },
            {
                "name": "OpenAI GPT-5 Mini",
                "description": "OpenAI GPT-5 Mini is a compact version of GPT-5 optimized for cost and speed.",
                "llm_key": "openai/gpt-5-mini",
                "integration_key": "openai",
                "model_name": "gpt-5-mini",
                "provider": "openai",
                "llm_config": {
                    "temperature": "__unsupported__",
                },
                "metadata": {
                    "max_tokens": 400000,
                    "max_output_tokens": 128000,
                    "intelligence": 4,
                    "speed": 4,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "structured_outputs",
                        "reasoning",
                    ],
                },
            },
            {
                "name": "OpenAI GPT-5 Nano",
                "description": "OpenAI GPT-5 Nano is the smallest and most efficient version of GPT-5.",
                "llm_key": "openai/gpt-5-nano",
                "integration_key": "openai",
                "model_name": "gpt-5-nano",
                "provider": "openai",
                "llm_config": {
                    "temperature": "__unsupported__",
                },
                "metadata": {
                    "max_tokens": 400000,
                    "max_output_tokens": 128000,
                    "intelligence": 3,
                    "speed": 5,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "structured_outputs",
                        "reasoning",
                    ],
                },
            },
            {
                "name": "OpenAI GPT-4.1",
                "description": "OpenAI GPT-4.1 is an advanced large language model with enhanced capabilities.",
                "llm_key": "openai/gpt-4.1",
                "integration_key": "openai",
                "model_name": "gpt-4.1",
                "provider": "openai",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 1047576,
                    "max_output_tokens": 32768,
                    "intelligence": 4,
                    "speed": 3,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "structured_outputs",
                    ],
                },
            },
            {
                "name": "OpenAI GPT-4.1 Mini",
                "description": "OpenAI GPT-4.1 Mini is a compact version of GPT-4.1 optimized for cost and speed.",
                "llm_key": "openai/gpt-4.1-mini",
                "integration_key": "openai",
                "model_name": "gpt-4.1-mini",
                "provider": "openai",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 1047576,
                    "max_output_tokens": 32768,
                    "intelligence": 3,
                    "speed": 4,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "structured_outputs",
                    ],
                },
            },
            {
                "name": "OpenAI GPT-4.1 Nano",
                "description": "OpenAI GPT-4.1 Nano is the smallest and most efficient version of GPT-4.1.",
                "llm_key": "openai/gpt-4.1-nano",
                "integration_key": "openai",
                "model_name": "gpt-4.1-nano",
                "provider": "openai",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 1047576,
                    "max_output_tokens": 32768,
                    "intelligence": 2,
                    "speed": 5,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "structured_outputs",
                    ],
                },
            },
            {
                "name": "OpenAI GPT-4o",
                "description": "OpenAI GPT-4o is a multimodal large language model with advanced reasoning capabilities.",
                "llm_key": "openai/gpt-4o",
                "integration_key": "openai",
                "model_name": "gpt-4o",
                "provider": "openai",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 128000,
                    "max_output_tokens": 16384,
                    "intelligence": 4,
                    "speed": 3,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "structured_outputs",
                    ],
                },
            },
            {
                "name": "OpenAI GPT-4o Mini",
                "description": "OpenAI GPT-4o Mini is a compact multimodal model optimized for cost-effective applications.",
                "llm_key": "openai/gpt-4o-mini",
                "integration_key": "openai",
                "model_name": "gpt-4o-mini",
                "provider": "openai",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 128000,
                    "max_output_tokens": 16384,
                    "intelligence": 3,
                    "speed": 4,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "structured_outputs",
                    ],
                },
            },
        ],
        "anthropic": [
            {
                "name": "Anthropic Claude Opus 4.7",
                "description": "Anthropic Claude Opus 4.7 is the most powerful model in the Claude Opus line with exceptional reasoning capabilities for complex and agentic workloads.",
                "llm_key": "anthropic/claude-opus-4-7",
                "integration_key": "anthropic",
                "model_name": "claude-opus-4-7",
                "provider": "anthropic",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 1000000,
                    "max_output_tokens": 128000,
                    "intelligence": 5,
                    "speed": 2,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                    ],
                },
            },
            {
                "name": "Anthropic Claude Sonnet 4.6",
                "description": "Anthropic Claude Sonnet 4.6 is the latest iteration with advanced capabilities, improved performance, and a strong balance of speed and intelligence.",
                "llm_key": "anthropic/claude-sonnet-4-6",
                "integration_key": "anthropic",
                "model_name": "claude-sonnet-4-6",
                "provider": "anthropic",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 1000000,
                    "max_output_tokens": 64000,
                    "intelligence": 4,
                    "speed": 3,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "extended_thinking",
                    ],
                },
            },
            {
                "name": "Anthropic Claude Opus 4.5",
                "description": "Anthropic Claude 4.5 Opus is the most powerful model in the Claude 4.5 family with exceptional reasoning capabilities.",
                "llm_key": "anthropic/claude-opus-4-5",
                "integration_key": "anthropic",
                "model_name": "claude-opus-4-5",
                "provider": "anthropic",
                "llm_config": {"thinking": {"type": "enabled", "budget_tokens": 2000}},
                "metadata": {
                    "max_tokens": 200000,
                    "max_output_tokens": 128000,
                    "intelligence": 5,
                    "speed": 2,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "extended_thinking",
                    ],
                },
            },
            {
                "name": "Anthropic Claude Sonnet 4.5",
                "description": "Anthropic Claude 4.5 Sonnet is the latest iteration with advanced capabilities and improved performance.",
                "llm_key": "anthropic/claude-sonnet-4-5",
                "integration_key": "anthropic",
                "model_name": "claude-sonnet-4-5",
                "provider": "anthropic",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 200000,
                    "max_output_tokens": 64000,
                    "intelligence": 4,
                    "speed": 3,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "extended_thinking",
                    ],
                },
            },
            {
                "name": "Anthropic Claude Haiku 4.5",
                "description": "Anthropic Claude 4.5 Haiku is the fastest and most compact model in the Claude 4.5 family.",
                "llm_key": "anthropic/claude-haiku-4-5",
                "integration_key": "anthropic",
                "model_name": "claude-haiku-4-5",
                "provider": "anthropic",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 200000,
                    "max_output_tokens": 64000,
                    "intelligence": 3,
                    "speed": 5,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "extended_thinking",
                    ],
                },
            },
        ],
        "google_genai": [
            {
                "name": "Google Gemini 3.1 Pro",
                "description": "Google Gemini 3.1 Pro is an advanced multimodal AI model with strong reasoning capabilities for complex problem-solving, coding, and agentic workflows.",
                "llm_key": "google_genai/gemini-3.1-pro-preview",
                "integration_key": "google_genai",
                "model_name": "gemini-3.1-pro-preview",
                "provider": "google_genai",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 1048576,
                    "max_output_tokens": 65536,
                    "intelligence": 5,
                    "speed": 3,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "multi_modal",
                        "reasoning",
                    ],
                },
            },
            {
                "name": "Google Gemini 3 Flash",
                "description": "Google Gemini 3 Flash is a fast and efficient multimodal AI model with frontier-class performance optimized for cost and latency.",
                "llm_key": "google_genai/gemini-3-flash-preview",
                "integration_key": "google_genai",
                "model_name": "gemini-3-flash-preview",
                "provider": "google_genai",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 1048576,
                    "max_output_tokens": 65536,
                    "intelligence": 4,
                    "speed": 5,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "multi_modal",
                        "reasoning",
                    ],
                },
            },
            {
                "name": "Google Gemini 3.1 Flash-Lite",
                "description": "Google Gemini 3.1 Flash-Lite is a compact multimodal model in the Gemini 3.1 family, optimized for cost-effective applications and high-volume workloads.",
                "llm_key": "google_genai/gemini-3.1-flash-lite-preview",
                "integration_key": "google_genai",
                "model_name": "gemini-3.1-flash-lite-preview",
                "provider": "google_genai",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 1048576,
                    "max_output_tokens": 65536,
                    "intelligence": 4,
                    "speed": 5,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "multi_modal",
                        "reasoning",
                    ],
                },
            },
            {
                "name": "Google Gemini 2.5 Pro",
                "description": "Google Gemini 2.5 Pro is an advanced multimodal AI model capable of deep reasoning over code, math, and STEM, and of analyzing large datasets, codebases, and documents using long context.",
                "llm_key": "google_genai/gemini-2.5-pro",
                "integration_key": "google_genai",
                "model_name": "gemini-2.5-pro",
                "provider": "google_genai",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 1048576,
                    "max_output_tokens": 65535,
                    "intelligence": 5,
                    "speed": 3,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "multi_modal",
                        "reasoning",
                    ],
                },
            },
            {
                "name": "Google Gemini 2.5 Flash",
                "description": "Google Gemini 2.5 Flash is a fast and efficient multimodal AI model with strong reasoning capabilities.",
                "llm_key": "google_genai/gemini-2.5-flash",
                "integration_key": "google_genai",
                "model_name": "gemini-2.5-flash",
                "provider": "google_genai",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 1048576,
                    "max_output_tokens": 65535,
                    "intelligence": 4,
                    "speed": 5,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "multi_modal",
                        "reasoning",
                    ],
                },
            },
            {
                "name": "Google Gemini 2.5 Flash-Lite",
                "description": "Google Gemini 2.5 Flash-Lite is the fastest and most cost-efficient multimodal model in the Gemini 2.5 family, optimized for high-volume and lightweight tasks.",
                "llm_key": "google_genai/gemini-2.5-flash-lite",
                "integration_key": "google_genai",
                "model_name": "gemini-2.5-flash-lite",
                "provider": "google_genai",
                "llm_config": {},
                "metadata": {
                    "max_tokens": 1048576,
                    "max_output_tokens": 65536,
                    "intelligence": 3,
                    "speed": 5,
                    "capabilities": [
                        "vision",
                        "tool_calling",
                        "multi_modal",
                        "reasoning",
                    ],
                },
            },
        ],
    }
]
