USER_ROLES = [
    {
        "name": "Account Admin",
        "role_key": "account_admin",
        "description": "Account admin with complete permissions",
        "default_role": True,
        "role_permissions": [
            "agents:view_agents",
            "agents:create_and_update_agents",
            "agent_llms:view_agent_llms",
            "agent_tools:view_agent_tools",
            "agent_tools:create_and_update_agent_tools",
            "agent_tools:delete_agent_tools",
            "api_keys:manage_api_keys",
            "assistant:assistant_chats",
            "assistant:scheduled_tasks",
            "class_groups:view_class_groups",
            "class_groups:create_and_update_class_groups",
            "class_groups:delete_class_groups",
            "collections:view_collections",
            "collections:create_and_update_collections",
            "collections:delete_collections",
            "dashboards:view_dashboards",
            "data_templates:view_data_templates",
            "data_templates:create_and_update_data_templates",
            "data_templates:delete_data_templates",
            "connections:view_connections",
            "connections:create_and_update_connections",
            "connections:delete_connections",
            "event_inbox:view_event_inbox",
            "event_inbox:create_and_update_event_inbox",
            "event_inbox:delete_event_inbox",
            "integration_catalog:view_integration_catalog",
            "integrations:view_integrations",
            "integrations:view_integration_credentials",
            "intents:view_intents",
            "intents:create_and_update_intents",
            "intents:delete_intents",
            "mailbox_pollings:view_mailbox_pollings",
            "mailbox_pollings:create_and_update_pollings",
            "mailbox_pollings:delete_mailbox_pollings",
            "organizations:view_organization",
            "organizations:update_organization",
            "task_inbox:view_task_inbox",
            "task_inbox:retry_email_tasks",
            "task_inbox:archive_email_tasks",
            "task_inbox:update_agent_tasks",
            "task_inbox:delete_email_tasks",
            "task_sources:view_task_sources",
            "task_sources:create_and_update_task_sources",
            "task_sources:delete_task_sources",
            "tool_bindings:view_tool_bindings",
            "tool_bindings:create_and_update_tool_bindings",
            "tool_bindings:delete_tool_bindings",
            "issues:view_issues",
            "issues:create_and_update_issues",
            "issues:delete_issues",
            "user_management:view_user_management",
            "user_management:create_and_update_user_management",
            "user_management:delete_user_management",
            "user_profile:manage_profile",
        ],
    },
    {
        "name": "System Admin",
        "role_key": "system_admin",
        "description": "System admin with high level permissions",
        "default_role": True,
        "role_permissions": [
            "agents:view_agents",
            "agent_llms:view_agent_llms",
            "agent_tools:view_agent_tools",
            "api_keys:manage_api_keys",
            "assistant:assistant_chats",
            "assistant:scheduled_tasks",
            "class_groups:view_class_groups",
            "collections:view_collections",
            "dashboards:view_dashboards",
            "data_templates:view_data_templates",
            "connections:view_connections",
            "event_inbox:view_event_inbox",
            "integration_catalog:view_integration_catalog",
            "intents:view_intents",
            "mailbox_pollings:view_mailbox_pollings",
            "mailbox_pollings:create_and_update_pollings",
            "organizations:view_organization",
            "organizations:update_organization",
            "task_inbox:view_task_inbox",
            "task_inbox:retry_email_tasks",
            "task_inbox:archive_email_tasks",
            "task_inbox:update_agent_tasks",
            "task_sources:view_task_sources",
            "tool_bindings:view_tool_bindings",
            "issues:view_issues",
            "issues:create_and_update_issues",
            "user_management:view_user_management",
            "user_management:create_and_update_user_management",
            "user_profile:manage_profile",
        ],
    },
    {
        "name": "Group Admin",
        "role_key": "group_admin",
        "description": "Group admin in the organization",
        "default_role": True,
        "role_permissions": [
            "agents:view_agents",
            "agent_llms:view_agent_llms",
            "agent_tools:view_agent_tools",
            "assistant:assistant_chats",
            "assistant:scheduled_tasks",
            "dashboards:view_dashboards",
            "organizations:view_organization",
            "task_inbox:view_task_inbox",
            "task_inbox:retry_email_tasks",
            "task_inbox:archive_email_tasks",
            "issues:view_issues",
            "user_profile:manage_profile",
        ],
    },
    {
        "name": "Group Staff",
        "role_key": "group_staff",
        "description": "Group staff in the organization",
        "default_role": True,
        "role_permissions": [
            "assistant:assistant_chats",
            "assistant:scheduled_tasks",
            "dashboards:view_dashboards",
            "organizations:view_organization",
            "task_inbox:view_task_inbox",
            "task_inbox:retry_email_tasks",
            "issues:view_issues",
            "user_profile:manage_profile",
        ],
    },
    {
        "name": "Standard User",
        "role_key": "standard_user",
        "description": "Standard user with limited access",
        "default_role": True,
        "role_permissions": [
            "assistant:assistant_chats",
            "assistant:scheduled_tasks",
            "dashboards:view_dashboards",
            "organizations:view_organization",
            "task_inbox:view_task_inbox",
            "issues:view_issues",
            "user_profile:manage_profile",
        ],
    },
]

MODULES = [
    {
        "module": "agents",
        "name": "Agents",
        "description": "Set of features used for reading and writing agents.",
    },
    {
        "module": "agent_llms",
        "name": "Agent LLMs",
        "description": "Set of features used for viewing agent LLMs.",
    },
    {
        "module": "agent_tools",
        "name": "Agent Tools",
        "description": "Set of features used for reading and writing agent tools.",
    },
    {
        "module": "api_keys",
        "name": "API Keys",
        "description": "Set of features used for managing API keys used for aceesing the platform via external systems.",
    },
    {
        "module": "assistant",
        "name": "Assistant",
        "description": "Set of features used for conversational chat and scheduled task execution.",
    },
    {
        "module": "class_groups",
        "name": "Class groups",
        "description": "Set of features used for reading and writing class groups.",
    },
    {
        "module": "collections",
        "name": "collections",
        "description": "Set of features used for reading and writing collection and data files",
    },
    {
        "module": "connections",
        "name": "Connections",
        "description": "Set of features used for viewing and managing integration connections.",
    },
    {
        "module": "dashboards",
        "name": "Dashboards",
        "description": "Set of features used in landing page / dashboards.",
    },
    {
        "module": "data_templates",
        "name": "Data templates",
        "description": "Set of features used for reading and writing data templates.",
    },
    {
        "module": "event_inbox",
        "name": "Event Inbox",
        "description": "Set of features used for viewing and managing event inbox items.",
    },
    {
        "module": "integration_catalog",
        "name": "Integration Catalog",
        "description": "Set of features used for viewing integration provider, auth schema and trigger catalogs.",
    },
    {
        "module": "integrations",
        "name": "Integrations",
        "description": "Set of features used for viewing integrations.",
    },
    {
        "module": "intents",
        "name": "Intents",
        "description": "Set of features used for reading and writing intents.",
    },
    {
        "module": "issues",
        "name": "Issues",
        "description": "Set of features used for viewing and managing issues.",
    },
    {
        "module": "mailbox_pollings",
        "name": "Mailbox pollings",
        "description": "Set of features used for creating, starting and stopping mailbox pollings.",
    },
    {
        "module": "organizations",
        "name": "Organizations",
        "description": "Set of features used for reading and writing organization information.",
    },
    {
        "module": "task_inbox",
        "name": "Task inbox",
        "description": "Set of features used for emails, attachments and agent outputs.",
    },
    {
        "module": "task_sources",
        "name": "Task Sources",
        "description": "Set of features used for viewing and managing task sources.",
    },
    {
        "module": "tool_bindings",
        "name": "Tool Bindings",
        "description": "Set of features used for viewing and managing tool bindings.",
    },
    {
        "module": "user_management",
        "name": "User Management",
        "description": "Set of features used for managing users, user roles, and user groups.",
    },
    {
        "module": "user_profile",
        "name": "User Profile",
        "description": "Set of features used for managing user profile.",
    },
]

PERMISSIONS = {
    "agents": [
        {
            "name": "View agents",
            "key": "view_agents",
            "description": "View AI agents on the platform",
            "endpoints": [
                "GET/agents",
                "GET/agents/search",
                "GET/agents/{agent_identifier}",
                "GET/agents/{agent_identifier}/export",
                "GET/agent-tools/{agent_tool_identifier}",
                "GET/agent/{agent_uuid}/agent-tools",
                "GET/version-histories",
                "GET/version-histories/{version_history_identifier}",
                "WEB/agents",
            ],
            "data_filters": ["name"],
        },
        {
            "name": "Create and update agents",
            "key": "create_and_update_agents",
            "description": "Create and update agents",
            "endpoints": [
                "GET/agents",
                "GET/agents/search",
                "GET/agents/{agent_identifier}",
                "GET/agents/{agent_identifier}/export",
                "POST/agents",
                "PUT/agents/{agent_uuid}",
                "POST/agents/import",
                "POST/agents/build",
                "POST/agents/archive",
                "GET/agent-tools",
                "GET/agent-tools/search",
                "GET/agent-tools/{agent_tool_identifier}",
                "GET/agent/{agent_uuid}/agent-tools",
                "GET/collections",
                "GET/collections/search",
                "GET/data-templates",
                "GET/data-templates/search",
                "GET/intents",
                "GET/intents-search",
                "GET/pollings",
                "GET/pollings/search",
                "GET/storage-mounts",
                "GET/version-histories",
                "GET/version-histories/{version_history_identifier}",
                "GET/integrations/llms",
                "WEB/agents",
            ],
            "data_filters": [],
        },
    ],
    "agent_llms": [
        {
            "name": "View agent LLMs",
            "key": "view_agent_llms",
            "description": "View agent LLMs on the platform",
            "endpoints": [
                "GET/agent-llms",
            ],
            "data_filters": [],
        },
    ],
    "agent_tools": [
        {
            "name": "View agent tools",
            "key": "view_agent_tools",
            "description": "View tools used by AI agents",
            "endpoints": [
                "GET/agent-tools",
                "GET/agent-tools/search",
                "GET/agent-tools/{agent_tool_identifier}",
                "GET/agent/{agent_uuid}/agent-tools",
                "GET/agent-tools/filters",
                "WEB/tools",
            ],
            "data_filters": [],
        },
        {
            "name": "Create and update agent tools",
            "key": "create_and_update_agent_tools",
            "description": "Create and update agent tools",
            "endpoints": [
                "GET/agent-tools",
                "GET/agent-tools/search",
                "GET/agent-tools/{agent_tool_identifier}",
                "GET/agent/{agent_uuid}/agent-tools",
                "POST/agent-tools",
                "PATCH/agent-tools/{agent_tool_uuid}",
                "POST/agent-tools/{agent_tool_identifier}/test",
                "WEB/tools",
            ],
            "data_filters": [],
        },
        {
            "name": "Delete agent tools",
            "key": "delete_agent_tools",
            "description": "Delete agent tools",
            "endpoints": [
                "GET/agent-tools",
                "GET/agent-tools/search",
                "GET/agent-tools/{agent_tool_identifier}",
                "GET/agent/{agent_uuid}/agent-tools",
                "DELETE/agent-tools/{agent_tool_identifier}",
                "WEB/tools",
            ],
            "data_filters": [],
        },
    ],
    "api_keys": [
        {
            "name": "Manage API keys",
            "key": "manage_api_keys",
            "description": "Manage API keys used for accessing the platform via external systems.",
            "endpoints": [
                "GET/api-keys",
                "GET/api-keys/search",
                "GET/api-keys/{api_key_identifier}",
                "POST/api-keys",
                "PATCH/api-keys/{api_key_uuid}",
                "DELETE/api-keys/{api_key_identifier}",
                "WEB/settings/api-keys",
            ],
            "data_filters": [],
        },
    ],
    "assistant": [
        {
            "name": "Assistant chats",
            "key": "assistant_chats",
            "description": "Assistant chats",
            "endpoints": [
                "POST/assistant/query",
                "GET/assistant/stream/{thread_id}",
                "GET/research/observe/{thread_id}",
                "POST/assistant/stream",
                "POST/research/stream",
                "GET/assistant/chat-threads",
                "GET/assistant/chat-threads/search",
                "GET/assistant/chat-threads/{chat_thread_identifier}",
                "GET/assistant/chat-threads/{chat_thread_uuid}/chat-messages",
                "POST/assistant/chat-threads",
                "PATCH/assistant/chat-threads/{chat_thread_uuid}",
                "POST/assistant/chat-messages",
                "PATCH/assistant/chat-messages/{chat_message_uuid}",
                "POST/assistant/chat-threads/{chat_thread_uuid}/{action}",
                "DELETE/assistant/chat-threads/{chat_thread_identifier}",
                "GET/assistant/private-data-collection",
                "GET/assistant/private-data-collection/search",
                "POST/assistant/private-data-files",
                "GET/assistant/collections",
                "GET/embedding-models",
                "GET/assistant/collections/search",
                "GET/assistant/collections/{collection_uuid}",
                "POST/assistant/collections",
                "PATCH/assistant/collections/{collection_uuid}",
                "POST/assistant/collections/{collection_uuid}/sharepoint-sites",
                "DELETE/assistant/collections/{collection_uuid}",
                "GET/assistant/data-files/{data_file_uuid}",
                "GET/assistant/data-files/{data_file_uuid}/knowledge",
                "GET/assistant/data-files/{data_file_uuid}/chunks",
                "GET/assistant/data-files/{data_file_uuid}/download",
                "POST/assistant/data-files",
                "POST/assistant/data-files/{data_file_uuid}/rename",
                "POST/assistant/data-files/{data_file_uuid}/reindex",
                "DELETE/assistant/data-files",
            ],
            "data_filters": [],
        },
        {
            "name": "Scheduled tasks",
            "key": "scheduled_tasks",
            "description": "Scheduled tasks",
            "endpoints": [
                "GET/assistant/tasks",
                "GET/assistant/tasks/search",
                "GET/assistant/tasks/{chat_thread_id}",
                "GET/assistant/tasks/{thread_uuid}/tasks",
                "POST/assistant/tasks",
                "PATCH/assistant/tasks/{chat_thread_id}",
                "POST/assistant/tasks/{chat_thread_id}/pause",
                "POST/assistant/tasks/{chat_thread_id}/resume",
                "DELETE/assistant/tasks/{chat_thread_id}",
                "GET/assistant/collections",
                "GET/assistant/collections/search",
                "GET/assistant/collections/{collection_uuid}",
                "POST/assistant/collections",
                "PATCH/assistant/collections/{collection_uuid}",
                "POST/assistant/collections/{collection_uuid}/sharepoint-sites",
                "DELETE/assistant/collections/{collection_uuid}",
                "GET/assistant/data-files/{data_file_uuid}",
                "GET/assistant/data-files/{data_file_uuid}/knowledge",
                "GET/assistant/data-files/{data_file_uuid}/chunks",
                "GET/assistant/data-files/{data_file_uuid}/download",
                "POST/assistant/data-files",
                "POST/assistant/data-files/{data_file_uuid}/rename",
                "POST/assistant/data-files/{data_file_uuid}/reindex",
                "DELETE/assistant/data-files",
            ],
            "data_filters": [],
        },
    ],
    "class_groups": [
        {
            "name": "View class groups",
            "key": "view_class_groups",
            "description": "View class groups",
            "endpoints": [
                "GET/class-groups",
                "GET/class-groups/search",
                "GET/class-groups/{class_group_identifier}",
                "WEB/settings/class-group",
            ],
            "data_filters": [],
        },
        {
            "name": "Create and update class groups",
            "key": "create_and_update_class_groups",
            "description": "Create and update class groups",
            "endpoints": [
                "GET/class-groups",
                "GET/class-groups/search",
                "GET/class-groups/{class_group_identifier}",
                "POST/class-groups",
                "PATCH/class-groups/{class_group_uuid}",
                "WEB/settings/class-group",
            ],
            "data_filters": [],
        },
        {
            "name": "Delete class groups",
            "key": "delete_class_groups",
            "description": "Delete class groups",
            "endpoints": [
                "GET/class-groups",
                "GET/class-groups/search",
                "GET/class-groups/{class_group_identifier}",
                "DELETE/class-groups/{class_group_identifier}",
                "WEB/settings/class-group",
            ],
            "data_filters": [],
        },
    ],
    "collections": [
        {
            "name": "View collections",
            "key": "view_collections",
            "description": "View collections and data files",
            "endpoints": [
                "GET/collections",
                "GET/collections/search",
                "GET/collections/{collection_uuid}",
                "GET/data-files/{data_file_uuid}",
                "GET/data-files/{data_file_uuid}/knowledge",
                "GET/data-files/{data_file_uuid}/chunks",
                "GET/collections/{collection_uuid}/knowledge-topics",
                "GET/collections/{collection_uuid}/smart-fields",
                "WEB/knowledge",
            ],
            "data_filters": ["name"],
        },
        {
            "name": "Create and update collections",
            "key": "create_and_update_collections",
            "description": "Create and update collections and data files",
            "endpoints": [
                "GET/collections",
                "GET/collections/search",
                "GET/collections/{collection_uuid}",
                "GET/data-files/{data_file_uuid}",
                "GET/data-files/{data_file_uuid}/knowledge",
                "GET/data-files/{data_file_uuid}/chunks",
                "GET/collections/{collection_uuid}/knowledge-topics",
                "GET/collections/{collection_uuid}/smart-fields",
                "GET/embedding-models",
                "POST/collections",
                "PATCH/collections/{collection_uuid}",
                "POST/collections/{collection_uuid}/sharepoint-sites",
                "GET/sharepoint/sites/{site_id}/objects",
                "GET/sharepoint/sites/{site_uuid}/{folder_id}/objects",
                "POST/sharepoint/files/import",
                "POST/data-files",
                "POST/data-files/{data_file_uuid}/rename",
                "POST/data-files/{data_file_uuid}/reindex",
                "GET/data-files/{data_file_uuid}/download",
                "POST/collections/{collection_uuid}/knowledge-topics",
                "PUT/collections/{collection_uuid}/knowledge-topics",
                "DELETE/collections/{collection_uuid}/knowledge-topics",
                "POST/collections/{collection_uuid}/smart-fields",
                "PUT/collections/{collection_uuid}/smart-fields",
                "DELETE/collections/{collection_uuid}/smart-fields",
                "GET/storage-mounts",
                "WEB/knowledge",
            ],
            "data_filters": [],
        },
        {
            "name": "Delete collections",
            "key": "delete_collections",
            "description": "Delete collections and data files",
            "endpoints": [
                "GET/collections",
                "GET/collections/search",
                "GET/collections/{collection_uuid}",
                "GET/data-files/{data_file_uuid}",
                "GET/data-files/{data_file_uuid}/knowledge",
                "GET/data-files/{data_file_uuid}/chunks",
                "GET/collections/{collection_uuid}/knowledge-topics",
                "GET/collections/{collection_uuid}/smart-fields",
                "DELETE/collections/{collection_uuid}",
                "DELETE/data-files",
                "WEB/knowledge",
            ],
            "data_filters": [],
        },
    ],
    "connections": [
        {
            "name": "View connections",
            "key": "view_connections",
            "description": "View integration connections",
            "endpoints": [
                "GET/connections",
                "GET/connections/{connection_id}",
                "WEB/connections",
            ],
            "data_filters": ["name", "provider_key", "auth_schema_key"],
        },
        {
            "name": "Create and update connections",
            "key": "create_and_update_connections",
            "description": "Create and update integration connections",
            "endpoints": [
                "GET/connections",
                "GET/connections/{connection_id}",
                "GET/connections/{connection_id}/credentials",
                "POST/connections",
                "POST/connections/{connection_id}/test",
                "PATCH/connections/{connection_id}",
                "WEB/connections",
            ],
            "data_filters": [],
        },
        {
            "name": "Delete connections",
            "key": "delete_connections",
            "description": "Soft delete integration connections",
            "endpoints": [
                "GET/connections",
                "GET/connections/{connection_id}",
                "GET/connections/{connection_id}/credentials",
                "DELETE/connections/{connection_id}",
                "WEB/connections",
            ],
            "data_filters": [],
        },
    ],
    "dashboards": [
        {
            "name": "View dashboards",
            "key": "view_dashboards",
            "description": "View dashboard data and stats",
            "endpoints": [
                "GET/email-counts",
                "GET/email-monthly-stats",
                "GET/task-agent-stats",
                "GET/count-by-mailbox",
                "GET/task-counts",
                "GET/task-monthly-stats",
                "GET/task-volume-stats",
                "WEB/",
            ],
            "data_filters": [],
        }
    ],
    "data_templates": [
        {
            "name": "View data templates",
            "key": "view_data_templates",
            "description": "View data templates",
            "endpoints": [
                "GET/data-templates",
                "GET/data-templates/search",
                "GET/data-templates/{data_template_identifier}",
                "GET/version-histories",
                "GET/version-histories/{version_history_identifier}",
                "WEB/settings/data-template",
            ],
            "data_filters": [],
        },
        {
            "name": "Create and update data templates",
            "key": "create_and_update_data_templates",
            "description": "Create and update data templates",
            "endpoints": [
                "GET/data-templates",
                "GET/data-templates/search",
                "GET/data-templates/{data_template_identifier}",
                "POST/data-templates",
                "PATCH/data-templates/{data_template_uuid}",
                "POST/data-templates/build-schema",
                "GET/version-histories",
                "GET/version-histories/{version_history_identifier}",
                "WEB/settings/data-template",
            ],
            "data_filters": [],
        },
        {
            "name": "Delete data templates",
            "key": "delete_data_templates",
            "description": "Delete data templates",
            "endpoints": [
                "GET/data-templates",
                "GET/data-templates/search",
                "GET/data-templates/{data_template_identifier}",
                "DELETE/data-templates/{data_template_identifier}",
                "WEB/settings/data-template",
            ],
            "data_filters": [],
        },
    ],
     "event_inbox": [
        {
            "name": "View event inbox",
            "key": "view_event_inbox",
            "description": "View event inbox items",
            "endpoints": [
                "GET/event-inboxes",
                "GET/event-inboxes/{event_inbox_id}",
                "WEB/event-inbox",
            ],
            "data_filters": ["external_event_id", "dedupe_key"],
        },
        {
            "name": "Create and update event inbox",
            "key": "create_and_update_event_inbox",
            "description": "Create and update event inbox items",
            "endpoints": [
                "GET/event-inboxes",
                "GET/event-inboxes/{event_inbox_id}",
                "POST/event-inboxes",
                "PATCH/event-inboxes/{event_inbox_id}",
                "WEB/event-inbox",
            ],
            "data_filters": [],
        },
        {
            "name": "Delete event inbox",
            "key": "delete_event_inbox",
            "description": "Delete event inbox items",
            "endpoints": [
                "GET/event-inboxes",
                "GET/event-inboxes/{event_inbox_id}",
                "DELETE/event-inboxes/{event_inbox_id}",
                "WEB/event-inbox",
            ],
            "data_filters": [],
        },
    ],
    "integration_catalog": [
        {
            "name": "View integration catalog",
            "key": "view_integration_catalog",
            "description": "View integration provider, auth schema, and trigger catalogs",
            "endpoints": [
                "GET/providers",
                "GET/auth-schema-catalog",
                "GET/trigger-catalog",
                "WEB/integration-catalog",
            ],
            "data_filters": ["keyword"],
        }
    ],
    "integrations": [
        {
            "name": "View integrations",
            "key": "view_integrations",
            "description": "View integrations",
            "endpoints": [
                "GET/integrations",
                "GET/integrations/search",
                "GET/integrations/tags",
                "GET/integrations/{integration_identifier}",
                "GET/integrations/{integration_identifier}/bindings",
                "WEB/integrations",
            ],
            "data_filters": [],
        },
        {
            "name": "View integration credentials",
            "key": "view_integration_credentials",
            "description": "View integration credentials",
            "endpoints": [
                "GET/integrations",
                "GET/integrations/search",
                "GET/integrations/tags",
                "GET/integrations/{integration_identifier}",
                "GET/integrations/{integration_identifier}/bindings",
                "GET/integrations/{integration_identifier}/credentials",
                "WEB/integrations",
            ],
            "data_filters": [],
        },
    ],
    "issues": [
        {
            "name": "View issues",
            "key": "view_issues",
            "description": "View issues and comments",
            "endpoints": [
                "GET/issues",
                "GET/issues/search",
                "GET/issues/filters",
                "GET/issues/filters/search",
                "GET/issues/{issue_uuid}",
                "GET/issues/{issue_uuid}/comments",
                "GET/issues/{issue_uuid}/agent-tasks",
                "GET/agent-tasks/{agent_task_uuid}/issues",
                "GET/emails/{email_uuid}/issues",
                "GET/comments/{comment_uuid}",
                "WEB/issues",
            ],
            "data_filters": [],
        },
        {
            "name": "Create and update issues",
            "key": "create_and_update_issues",
            "description": "Create and update issues and comments",
            "endpoints": [
                "GET/issues",
                "GET/issues/search",
                "GET/issues/filters",
                "GET/issues/filters/search",
                "GET/issues/{issue_uuid}",
                "GET/issues/{issue_uuid}/comments",
                "GET/issues/{issue_uuid}/agent-tasks",
                "GET/agent-tasks/{agent_task_uuid}/issues",
                "GET/emails/{email_uuid}/issues",
                "GET/comments/{comment_uuid}",
                "POST/issues",
                "PATCH/issues/{issue_uuid}",
                "PATCH/issues/{issue_uuid}/{action}",
                "PUT/issues/{issue_uuid}/progress",
                "POST/comments",
                "PATCH/comments/{comment_uuid}",
                "WEB/issues",
            ],
            "data_filters": [],
        },
        {
            "name": "Delete issues",
            "key": "delete_issues",
            "description": "Delete issues and comments",
            "endpoints": [
                "GET/issues",
                "GET/issues/search",
                "GET/issues/filters",
                "GET/issues/filters/search",
                "GET/issues/{issue_uuid}",
                "GET/issues/{issue_uuid}/comments",
                "GET/issues/{issue_uuid}/agent-tasks",
                "GET/agent-tasks/{agent_task_uuid}/issues",
                "GET/emails/{email_uuid}/issues",
                "GET/comments/{comment_uuid}",
                "DELETE/issues/{issue_uuid}",
                "DELETE/comments/{comment_uuid}",
                "WEB/issues",
            ],
            "data_filters": [],
        },
    ],
    "intents": [
        {
            "name": "View intents",
            "key": "view_intents",
            "description": "View intents",
            "endpoints": [
                "GET/intents",
                "GET/intents-search",
                "GET/intents/{intent_identifier}",
                "WEB/settings/intent-class",
            ],
            "data_filters": [],
        },
        {
            "name": "Create and update intents",
            "key": "create_and_update_intents",
            "description": "Create and update intents",
            "endpoints": [
                "GET/intents",
                "GET/intents-search",
                "GET/intents/{intent_identifier}",
                "POST/intents",
                "POST/intents/{intent_uuid}",
                "WEB/settings/intent-class",
            ],
            "data_filters": [],
        },
        {
            "name": "Delete intents",
            "key": "delete_intents",
            "description": "Delete intents",
            "endpoints": [
                "GET/intents",
                "GET/intents-search",
                "GET/intents/{intent_identifier}",
                "DELETE/intents/{intent_identifier}",
                "WEB/settings/intent-class",
            ],
            "data_filters": [],
        },
    ],
    "mailbox_pollings": [
        {
            "name": "View mailbox pollings",
            "key": "view_mailbox_pollings",
            "description": "View list of polled mailboxes",
            "endpoints": [
                "GET/pollings",
                "GET/pollings/search",
                "GET/pollings/{polling_identifier}",
                "WEB/settings/mailbox-polling",
            ],
            "data_filters": [],
        },
        {
            "name": "Create and update pollings",
            "key": "create_and_update_pollings",
            "description": "Create and update mailbox pollings",
            "endpoints": [
                "GET/pollings",
                "GET/pollings/search",
                "GET/pollings/{polling_identifier}",
                "POST/pollings",
                "PATCH/pollings/{polling_identifier}",
                "POST/pollings/{polling_identifier}/start",
                "POST/pollings/{polling_identifier}/stop",
                "GET/storage-mounts",
                "WEB/settings/mailbox-polling",
            ],
            "data_filters": [],
        },
        {
            "name": "Delete mailbox pollings",
            "key": "delete_mailbox_pollings",
            "description": "Delete mailbox pollings",
            "endpoints": [
                "GET/pollings",
                "GET/pollings/search",
                "GET/pollings/{polling_identifier}",
                "DELETE/pollings/{polling_identifier}",
                "WEB/settings/mailbox-polling",
            ],
            "data_filters": [],
        },
    ],
    "organizations": [
        {
            "name": "View organization",
            "key": "view_organization",
            "description": "View organization details",
            "endpoints": [
                "GET/organizations/current",
                "GET/configurations",
                "WEB/settings/account",
            ],
            "data_filters": [],
        },
        {
            "name": "Update organization",
            "key": "update_organization",
            "description": "Update organization details",
            "endpoints": [
                "GET/organizations/current",
                "GET/configurations",
                "PATCH/organizations/current",
                "POST/configurations",
                "GET/storage-mounts",
                "GET/agent-llms",
                "WEB/settings/account",
            ],
            "data_filters": [],
        },
    ],
    "task_inbox": [
        {
            "name": "View task inbox",
            "key": "view_task_inbox",
            "description": "View task inbox on this platform",
            "endpoints": [
                "GET/emails",
                "GET/emails/search",
                "POST/emails/export",
                "POST/agent-tasks/export",
                "GET/emails/{email_uuid}",
                "GET/emails/filters",
                "GET/agents/preview",
                "GET/emails/{email_uuid}/agent-tasks",
                "GET/emails/{email_uuid}/task-events",
                "GET/emails/{email_uuid}/attachments",
                "GET/attachments/{attachment_identifier}",
                "GET/attachments/{attachment_identifier}/view",
                "GET/attachments/{attachment_identifier}/view-images",
                "GET/attachments/{attachment_identifier}/download",
                "GET/data-templates/{data_template_identifier}",
                "GET/task-outputs/{agent_task_uuid}",
                "GET/task-outputs/{agent_task_uuid}/usage",
                "GET/agent-outputs/{agent_task_uuid}/{agent_uuid}",
                "GET/agent-outputs/{agent_output_uuid}",
                "GET/task-progress/{email_uuid}",
                "GET/task-progress-search/{email_uuid}",
                "GET/agent-tasks/{agent_task_uuid}",
                "GET/agent-tasks/{agent_task_uuid}/stream",
                "POST/agent-tasks/{agent_task_uuid}/continue",
                "POST/agent-tasks/{agent_task_uuid}/resume",
                "GET/entities/{entity_id}/activity-logs",
                "PATCH/emails/{email_uuid}/tags",
                "POST/agent-tasks/{agent_task_uuid}/tags",
                "GET/tags",
                "GET/tags/search",
                "GET/tags/{tag_identifier}",
                "POST/tags",
                "PATCH/tags/{tag_uuid}",
                "DELETE/tags/{tag_identifier}",
                "GET/agent-tasks/{agent_task_uuid}/issues",
                "GET/emails/{email_uuid}/issues",
                "GET/issues/{issue_uuid}",
                "GET/issues/{issue_uuid}/comments",
                "GET/issues/{issue_uuid}/agent-tasks",
                "GET/comments/{comment_uuid}",
                "POST/issues",
                "PATCH/issues/{issue_uuid}",
                "PATCH/issues/{issue_uuid}/{action}",
                "PUT/issues/{issue_uuid}/progress",
                "POST/comments",
                "PATCH/comments/{comment_uuid}",
                "WEB/inbox",
            ],
            "data_filters": ["mailbox_email"],
        },
        {
            "name": "Retry email tasks",
            "key": "retry_email_tasks",
            "description": "Retry email tasks",
            "endpoints": [
                "GET/emails",
                "GET/emails/search",
                "POST/emails/export",
                "POST/agent-tasks/export",
                "GET/emails/{email_uuid}",
                "GET/emails/filters",
                "GET/agents/preview",
                "GET/emails/{email_uuid}/agent-tasks",
                "GET/emails/{email_uuid}/task-events",
                "GET/emails/{email_uuid}/attachments",
                "GET/attachments/{attachment_identifier}",
                "GET/attachments/{attachment_identifier}/view",
                "GET/attachments/{attachment_identifier}/view-images",
                "GET/attachments/{attachment_identifier}/download",
                "GET/data-templates/{data_template_identifier}",
                "GET/task-outputs/{agent_task_uuid}",
                "GET/task-outputs/{agent_task_uuid}/usage",
                "GET/agent-outputs/{agent_task_uuid}/{agent_uuid}",
                "GET/agent-outputs/{agent_output_uuid}",
                "GET/task-progress/{email_uuid}",
                "GET/task-progress-search/{email_uuid}",
                "GET/agent-tasks/{agent_task_uuid}",
                "GET/agent-tasks/{agent_task_uuid}/stream",
                "POST/agent-tasks/{agent_task_uuid}/continue",
                "POST/agent-tasks/{agent_task_uuid}/resume",
                "POST/agent-tasks/{agent_task_uuid}/retry",
                "GET/entities/{entity_id}/activity-logs",
                "PATCH/emails/{email_uuid}/tags",
                "POST/agent-tasks/{agent_task_uuid}/tags",
                "GET/tags",
                "GET/tags/search",
                "GET/tags/{tag_identifier}",
                "POST/tags",
                "PATCH/tags/{tag_uuid}",
                "DELETE/tags/{tag_identifier}",
                "POST/emails/{agent_task_uuid}/retry/{agent_id}",
                "POST/emails/{email_uuid}/reprocess",
                "POST/attachments/{attachment_uuid}/reprocess",
                "GET/agent-tasks/{agent_task_uuid}/issues",
                "GET/emails/{email_uuid}/issues",
                "GET/issues/{issue_uuid}",
                "GET/issues/{issue_uuid}/comments",
                "GET/issues/{issue_uuid}/agent-tasks",
                "GET/comments/{comment_uuid}",
                "POST/issues",
                "PATCH/issues/{issue_uuid}",
                "PATCH/issues/{issue_uuid}/{action}",
                "PUT/issues/{issue_uuid}/progress",
                "POST/comments",
                "PATCH/comments/{comment_uuid}",
            ],
            "data_filters": [],
        },
        {
            "name": "Archive email tasks",
            "key": "archive_email_tasks",
            "description": "Archive email tasks",
            "endpoints": [
                "GET/emails",
                "GET/emails/search",
                "POST/emails/export",
                "POST/agent-tasks/export",
                "GET/emails/{email_uuid}",
                "GET/emails/filters",
                "GET/agents/preview",
                "GET/emails/{email_uuid}/agent-tasks",
                "GET/emails/{email_uuid}/task-events",
                "GET/emails/{email_uuid}/attachments",
                "GET/attachments/{attachment_identifier}",
                "GET/attachments/{attachment_identifier}/view",
                "GET/attachments/{attachment_identifier}/view-images",
                "GET/attachments/{attachment_identifier}/download",
                "GET/data-templates/{data_template_identifier}",
                "GET/task-outputs/{agent_task_uuid}",
                "GET/task-outputs/{agent_task_uuid}/usage",
                "GET/agent-outputs/{agent_task_uuid}/{agent_uuid}",
                "GET/agent-outputs/{agent_output_uuid}",
                "GET/task-progress/{email_uuid}",
                "GET/task-progress-search/{email_uuid}",
                "GET/agent-tasks/{agent_task_uuid}",
                "GET/agent-tasks/{agent_task_uuid}/stream",
                "POST/agent-tasks/{agent_task_uuid}/continue",
                "POST/agent-tasks/{agent_task_uuid}/resume",
                "GET/entities/{entity_id}/activity-logs",
                "PATCH/emails/{email_uuid}/tags",
                "POST/agent-tasks/{agent_task_uuid}/tags",
                "GET/tags",
                "GET/tags/search",
                "GET/tags/{tag_identifier}",
                "POST/tags",
                "PATCH/tags/{tag_uuid}",
                "DELETE/tags/{tag_identifier}",
                "POST/emails/archive",
                "GET/agent-tasks/{agent_task_uuid}/issues",
                "GET/emails/{email_uuid}/issues",
                "GET/issues/{issue_uuid}",
                "GET/issues/{issue_uuid}/comments",
                "GET/issues/{issue_uuid}/agent-tasks",
                "GET/comments/{comment_uuid}",
                "POST/issues",
                "PATCH/issues/{issue_uuid}",
                "PATCH/issues/{issue_uuid}/{action}",
                "PUT/issues/{issue_uuid}/progress",
                "POST/comments",
                "PATCH/comments/{comment_uuid}",
            ],
            "data_filters": [],
        },
        {
            "name": "Update agent tasks",
            "key": "update_agent_tasks",
            "description": "Update agent tasks and its related data",
            "endpoints": [
                "GET/emails",
                "GET/emails/search",
                "POST/emails/export",
                "POST/agent-tasks/export",
                "GET/emails/{email_uuid}",
                "GET/emails/filters",
                "GET/agents/preview",
                "GET/emails/{email_uuid}/agent-tasks",
                "GET/emails/{email_uuid}/task-events",
                "GET/emails/{email_uuid}/attachments",
                "GET/attachments/{attachment_identifier}",
                "GET/attachments/{attachment_identifier}/view",
                "GET/attachments/{attachment_identifier}/view-images",
                "GET/attachments/{attachment_identifier}/download",
                "GET/data-templates/{data_template_identifier}",
                "GET/task-outputs/{agent_task_uuid}",
                "GET/task-outputs/{agent_task_uuid}/usage",
                "GET/agent-outputs/{agent_task_uuid}/{agent_uuid}",
                "GET/agent-outputs/{agent_output_uuid}",
                "GET/task-progress/{email_uuid}",
                "GET/task-progress-search/{email_uuid}",
                "GET/agent-tasks/{agent_task_uuid}",
                "GET/agent-tasks/{agent_task_uuid}/stream",
                "POST/agent-tasks/{agent_task_uuid}/continue",
                "POST/agent-tasks/{agent_task_uuid}/resume",
                "GET/entities/{entity_id}/activity-logs",
                "PATCH/emails/{email_uuid}/tags",
                "POST/agent-tasks/{agent_task_uuid}/tags",
                "GET/tags",
                "GET/tags/search",
                "GET/tags/{tag_identifier}",
                "POST/tags",
                "PATCH/tags/{tag_uuid}",
                "DELETE/tags/{tag_identifier}",
                "POST/agent-tasks/status",
                "GET/agent-tasks/{agent_task_uuid}/issues",
                "GET/emails/{email_uuid}/issues",
                "GET/issues/{issue_uuid}",
                "GET/issues/{issue_uuid}/comments",
                "GET/issues/{issue_uuid}/agent-tasks",
                "GET/comments/{comment_uuid}",
                "POST/issues",
                "PATCH/issues/{issue_uuid}",
                "PATCH/issues/{issue_uuid}/{action}",
                "PUT/issues/{issue_uuid}/progress",
                "POST/comments",
                "PATCH/comments/{comment_uuid}",
            ],
            "data_filters": [],
        },
        {
            "name": "Delete email tasks",
            "key": "delete_email_tasks",
            "description": "Delete email tasks and its related data",
            "endpoints": [
                "GET/emails",
                "GET/emails/search",
                "POST/emails/export",
                "POST/agent-tasks/export",
                "GET/emails/{email_uuid}",
                "GET/emails/filters",
                "GET/agents/preview",
                "GET/emails/{email_uuid}/agent-tasks",
                "GET/emails/{email_uuid}/task-events",
                "GET/emails/{email_uuid}/attachments",
                "GET/attachments/{attachment_identifier}",
                "GET/attachments/{attachment_identifier}/view",
                "GET/attachments/{attachment_identifier}/view-images",
                "GET/attachments/{attachment_identifier}/download",
                "GET/data-templates/{data_template_identifier}",
                "GET/task-outputs/{agent_task_uuid}",
                "GET/task-outputs/{agent_task_uuid}/usage",
                "GET/agent-outputs/{agent_task_uuid}/{agent_uuid}",
                "GET/agent-outputs/{agent_output_uuid}",
                "GET/task-progress/{email_uuid}",
                "GET/task-progress-search/{email_uuid}",
                "GET/agent-tasks/{agent_task_uuid}",
                "GET/agent-tasks/{agent_task_uuid}/stream",
                "POST/agent-tasks/{agent_task_uuid}/continue",
                "POST/agent-tasks/{agent_task_uuid}/resume",
                "GET/entities/{entity_id}/activity-logs",
                "PATCH/emails/{email_uuid}/tags",
                "POST/agent-tasks/{agent_task_uuid}/tags",
                "GET/tags",
                "GET/tags/search",
                "GET/tags/{tag_identifier}",
                "POST/tags",
                "PATCH/tags/{tag_uuid}",
                "DELETE/tags/{tag_identifier}",
                "DELETE/emails/bulk",
                "GET/agent-tasks/{agent_task_uuid}/issues",
                "GET/emails/{email_uuid}/issues",
                "GET/issues/{issue_uuid}",
                "GET/issues/{issue_uuid}/comments",
                "GET/issues/{issue_uuid}/agent-tasks",
                "GET/comments/{comment_uuid}",
                "POST/issues",
                "PATCH/issues/{issue_uuid}",
                "PATCH/issues/{issue_uuid}/{action}",
                "PUT/issues/{issue_uuid}/progress",
                "POST/comments",
                "PATCH/comments/{comment_uuid}",
                "DELETE/issues/{issue_uuid}",
                "DELETE/comments/{comment_uuid}",
                "WEB/inbox",
            ],
            "data_filters": [],
        },
    ],
    "task_sources": [
        {
            "name": "View task sources",
            "key": "view_task_sources",
            "description": "View task sources",
            "endpoints": [
                "GET/task-sources",
                "GET/task-sources/{task_source_id}",
                "WEB/task-sources",
            ],
            "data_filters": ["name", "provider_key", "trigger_key"],
        },
        {
            "name": "Create and update task sources",
            "key": "create_and_update_task_sources",
            "description": "Create and update task sources",
            "endpoints": [
                "GET/task-sources",
                "GET/task-sources/{task_source_id}",
                "POST/task-sources",
                "PATCH/task-sources/{task_source_id}",
                "WEB/task-sources",
            ],
            "data_filters": [],
        },
        {
            "name": "Delete task sources",
            "key": "delete_task_sources",
            "description": "Delete task sources",
            "endpoints": [
                "GET/task-sources",
                "GET/task-sources/{task_source_id}",
                "DELETE/task-sources/{task_source_id}",
                "WEB/task-sources",
            ],
            "data_filters": [],
        },
    ],
    "tool_bindings": [
        {
            "name": "View tool bindings",
            "key": "view_tool_bindings",
            "description": "View tool bindings",
            "endpoints": [
                "GET/tool-bindings",
                "GET/tool-bindings/{tool_binding_id}",
                "WEB/tool-bindings",
            ],
            "data_filters": ["provider_key", "tool_key"],
        },
        {
            "name": "Create and update tool bindings",
            "key": "create_and_update_tool_bindings",
            "description": "Create and update tool bindings",
            "endpoints": [
                "GET/tool-bindings",
                "GET/tool-bindings/{tool_binding_id}",
                "POST/tool-bindings",
                "PATCH/tool-bindings/{tool_binding_id}",
                "WEB/tool-bindings",
            ],
            "data_filters": [],
        },
        {
            "name": "Delete tool bindings",
            "key": "delete_tool_bindings",
            "description": "Delete tool bindings",
            "endpoints": [
                "GET/tool-bindings",
                "GET/tool-bindings/{tool_binding_id}",
                "DELETE/tool-bindings/{tool_binding_id}",
                "WEB/tool-bindings",
            ],
            "data_filters": [],
        },
    ],
    "user_management": [
        {
            "name": "View user management",
            "key": "view_user_management",
            "description": "View users, user roles, and user groups",
            "endpoints": [
                "GET/users",
                "GET/users/search",
                "GET/users/{user_identifier}",
                "GET/user-roles",
                "GET/user-roles/search",
                "GET/permissions",
                "GET/user-groups",
                "GET/user-groups/search",
                "GET/user-groups/{user_group_identifier}",
                "WEB/settings/manage-user",
            ],
            "data_filters": [],
        },
        {
            "name": "Create and update user management",
            "key": "create_and_update_user_management",
            "description": "Create and update users, user roles, and user groups",
            "endpoints": [
                "GET/users",
                "GET/users/search",
                "GET/users/{user_identifier}",
                "POST/users",
                "PATCH/users/{user_uuid}",
                "POST/users/{user_uuid}/{action}",
                "GET/user-roles",
                "GET/user-roles/search",
                "GET/permissions",
                "POST/user-roles",
                "PATCH/user-roles/{user_role_uuid}",
                "GET/user-groups",
                "GET/user-groups/search",
                "GET/user-groups/{user_group_identifier}",
                "POST/user-groups",
                "PATCH/user-groups/{user_group_uuid}",
                "GET/user-roles/{user_role_uuid}/data-access-permissions",
                "GET/permissions/data-access",
                "GET/app-access",
                "WEB/settings/manage-user",
            ],
            "data_filters": [],
        },
        {
            "name": "Delete user management",
            "key": "delete_user_management",
            "description": "Delete users, user roles, and user groups",
            "endpoints": [
                "GET/users",
                "GET/users/search",
                "GET/users/{user_identifier}",
                "DELETE/users/{user_uuid}",
                "GET/user-roles",
                "GET/user-roles/search",
                "DELETE/user-roles/{user_role_uuid}",
                "GET/user-groups",
                "GET/user-groups/search",
                "GET/user-groups/{user_group_identifier}",
                "DELETE/user-groups/{user_group_uuid}",
                "WEB/settings/manage-user",
            ],
            "data_filters": [],
        },
    ],
    "user_profile": [
        {
            "name": "Manage profile",
            "key": "manage_profile",
            "description": "View and edit user profile",
            "endpoints": [
                "GET/profile/office365",
                "GET/profile",
                "PATCH/profile",
                "PUT/profile/password",
                "WEB/profile",
            ],
            "data_filters": [],
        },
    ],
}

# APP_ACCESS = [
#     {
#         "key": "web_application",
#         "name": "Web Application",
#         "description": "Grants access to the Web Application for managing emails and tasks.",
#     }
# ]
APP_ACCESS = []
